const fs = require('fs');

// Example requires – adapt to your actual locations
const files = require('../utils/files');
const schemas = require('../processors/schemas');
const tables = require('../processors/tables');
const others = require('../processors/others');
const functions = require('../processors/functions');
const procedures = require('../processors/procedures');
const inserts = require('../processors/inserts');
const updates = require('../processors/updates');


/**
 * generateCommand:
 *  1) Collect/scan all relevant SQL parts (schemas, tables, etc.)
 *  2) Construct the final “alter” script
 *  3) Write to config.output_file
 */
async function generateCommand(config) {

    let alter = '';

    // SCHEMAS
    const schemaFiles = files.listfiles('schemas', 'all');
    schemas.process(schemaFiles);

    // TABLES
    const tableFiles = files.listfiles('tables', 'all');
    tables.process(tableFiles);

    // VIEWS 
    const viewFiles = files.listfiles('views', 'all');
    others.process('views', viewFiles);

    // FUNCTIONS
    const functionFiles = files.listfiles('functions', 'all');
    others.process('functions', functionFiles);

    // PROCEDURES
    const procedurFiles = files.listfiles('procedures', 'all');
    others.process('procedures', procedurFiles);


    // TRIGGERS
    const triggerFiles = files.listfiles('triggers', 'all');


    // SEQUENCES
    const sequenceFiles = files.listfiles('sequences', 'all');


    // TYPES
    const typeFiles = files.listfiles('types', 'all');

    // EXTENSIONS
    const extensionFiles = files.listfiles('extensions', 'all');

    // INSERTS
    const insertFiles = files.listfiles('inserts', 'all');
    let insertsRes = await inserts.generate(insertFiles);

    // UPDATES
    const updateFiles = files.listfiles('updates', 'all');
    let updatesRes = await updates.generate(updateFiles);



    let schemasRes = schemas.generate();
    let tablesRes = tables.generate();
    let otherRes = others.generate();
    let dropRes = others.drop();





    // let tablesRes = tables.generate();


    // const othersRes = others.generate(othersFiles);


    // // INDEXES
    // const indexFiles = files.listfiles('tables', 'all');
    // alter += indexes.generate(indexFiles) + '\n-- step\n';

    // // INSERTS
    // const insertFiles = files.listfiles('inserts', 'all');
    // alter += insert.generate(insertFiles);


    // Merge portions
    alter += [
        ...schemasRes,
        ...tablesRes.drop_constraints,
        ...dropRes,
        ...tablesRes.create,
        ...tablesRes.constraints,
        ...otherRes,
        ...insertsRes,
        ...updatesRes,
    ].join('\n-- step\n') + '\n-- step\n';

    // Final version label + note
    const version = require('../../package.json').version;
    const now = new Date().toISOString();
    let note =
        `-- This file was generated by pg-altergen v${version}\n-- ${now}\n\n` +
        `-- with config:\n\n-- The MIT License (MIT)\n-- © 2024 Marek Mráz <info@marek-mraz.com>\n\n`;

    // Copy config minus the Postgres password or other sensitive data
    const configCopy = { ...config };
    delete configCopy.postgres;

    for (let key in configCopy) {
        note += `--   ${key}: ${JSON.stringify(configCopy[key])}\n`;
    }

    // Write everything to disk
    fs.writeFileSync(config.output_file, note + '\n' + alter + '\n' + note);
    console.log(`Generated SQL file: ${config.output_file}`);
}

module.exports = { generateCommand }; 